name: gitartwork from contribution graph

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jasineri/gitartwork@v1
        with:
          user_name: saitejabasudi
          text: THANKS FOR VISITING

      - uses: jasineri/simple-push-action@v1
        with:
          branch: main
